AWS:
  IAMRole: "alpha_nfs_backup"
  S3:
    BucketName: "alpha-moj-analytics-nfs-backup"
Image:
  Repository: amazon/aws-cli
  Tag: 2.0.31
  PullPolicy: IfNotPresent
Schedule: "@daily"
successfulJobsHistoryLimit: 5
failedJobsHistoryLimit: 5
