apiVersion: v1
appVersion: 2.273.5
description: Self-hosted GitHub Actions Runner
name: github-actions-runner
version: 0.4.1
type: application
keywords:
  - github
sources:
  - https://github.com/ministryofjustice/analytics-platform-helm-charts/tree/main/charts/github-actions-runner
  - https://github.com/myoung34/docker-github-actions-runner
